apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  sources:
    - chart: elasticsearch
      repoURL: https://helm.elastic.co
      targetRevision: 7.17.3
      helm:
        valueFiles:
        - $values/elasticsearch_values.yaml
    - repoURL: 'https://github.com/Fahras23/helm_values.git'
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring