apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  project: default
  sources:
    - chart: fluent-bit
      repoURL: https://fluent.github.io/helm-charts
      targetRevision: 0.48.9
      helm:
        valueFiles:
        - $values/fluentbit_values.yaml
    - repoURL: 'https://github.com/Fahras23/helm_values.git'
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring