apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  project: default
  sources:
    - chart: fluent-bit
      repoURL: https://fluent.github.io/helm-charts
      targetRevision: 0.48.9
      helm:
        releaseName: fluent-bit
        valueFiles:
          - Apps/monitoring/helm_values/fluentbit-values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring