apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Fahras23/Devops-lab.git
      targetRevision: HEAD
      path: Apps/monitoring
    - repoURL: https://github.com/Fahras23/Devops-lab.git
      targetRevision: HEAD
      path: Apps/monitoring/helm_values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true