apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatapp-beta
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Fahras23/Devops-lab.git
    targetRevision: HEAD
    path: Apps/chatapp/overlays/beta
  destination:
    server: https://kubernetes.default.svc
    namespace: beta
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: beta-image-updater
  namespace: argocd
spec:
  namespace: argocd  # Target namespace where Argo CD Applications are located
  applicationRefs:
    - namePattern: "chatapp-beta"  # Select applications matching this pattern
      images:
        - alias: "chatapp-beta"
          imageName: "kyczak/chatapp:beta"
          commonUpdateSettings:
            updateStrategy: digest
            forceUpdate: true
  writeBackConfig:
    method: git:secret:argocd/git-creds
    gitConfig:
      branch: master