apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatapp-prod
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: chatapp-image=kyczak/chatapp
    argocd-image-updater.argoproj.io/chatapp-image.update-strategy: latest
    argocd-image-updater.argoproj.io/chatapp-image.force-update: "true"
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: master
spec:
  project: default
  source:
    repoURL: https://github.com/Fahras23/Devops-lab.git
    targetRevision: HEAD
    path: Apps/chatapp/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true