apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatapp-beta
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: chatapp-image=kyczak/chatapp:beta
    argocd-image-updater.argoproj.io/chatapp-image.update-strategy: digest #update to latest image with declared tag
    argocd-image-updater.argoproj.io/chatapp-image.force-update: "true"
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: master
spec:
  project: default
  source:
    repoURL: https://github.com/Fahras23/Devops-lab.git
    targetRevision: HEAD
    path: Apps/chatapp/overlays/beta
  destination:
    server: https://kubernetes.default.svc
    namespace: beta
  syncPolicy:
    automated:
      prune: true
      selfHeal: true