apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatapp
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: kyczak/chatapp
    argocd-image-updater.argoproj.io/chatapp.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: master
spec:
  project: default
  source:
    repoURL: https://github.com/Fahras23/Devops-lab.git
    targetRevision: HEAD
    path: Apps/base/chatapp
  destination:
    server: https://kubernetes.default.svc
    namespace: chatapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true