apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: beta
spec:
  template:
    spec:
      containers:
        - name: db-migration
          image: kyczak/chatapp:beta
          command: ["python", "manage.py", "migrate"]
          env:
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: beta-pg-cluster-app
                key: dbname
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: beta-pg-cluster-app
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: beta-pg-cluster-app
                key: password
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: beta-pg-cluster-app
                key: host
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: beta-pg-cluster-app
                key: port
      restartPolicy: OnFailure