apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
  # for maintenance window
  # nodeMaintenanceWindow:
  #   inProgress: true
  #   reusePVC: true