apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  enableServiceMonitor: true
  enablePodMonitor: true
  metrics:
    enable: true
    interval: 10s
  # for maintenance window
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  backup:
    barmanObjectStore:
      destinationPath: "https://kubernetesstorage25.blob.core.windows.net/cnpg-backups/backups"
      azureCredentials:
        storageAccount:
          name: azure-creds
          key: AZURE_STORAGE_ACCOUNT
        storageKey:
          name: azure-creds
          key: AZURE_STORAGE_KEY
      wal:
        compression: gzip