apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
    metrics:
      enable: true
      interval: 10s
    customQueries:
      - name: pg_users
        query: |
          SELECT count(*) FROM auth_user;
        metrics:
        - metric: "pg_users"
          description: "PostgreSQL users information"
          
  # for maintenance window
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  backup:
    barmanObjectStore:
      destinationPath: "https://kubestrg.blob.core.windows.net/cnpg-backups/backups"
      azureCredentials:
        storageAccount:
          name: azure-creds
          key: AZURE_STORAGE_ACCOUNT
        storageKey:
          name: azure-creds
          key: AZURE_STORAGE_KEY
      wal:
        compression: gzip