apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  bootstrap:
    recovery:
      backup:
        name: beta-pg-backup-schedule-20250312104855
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
  # for maintenance window
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  backup:
    barmanObjectStore:
      destinationPath: "https://kubernetesstorages.blob.core.windows.net/cnpg-backups/backups"
      azureCredentials:
        storageAccount:
          name: azure-creds
          key: AZURE_STORAGE_ACCOUNT
        storageKey:
          name: azure-creds
          key: AZURE_STORAGE_KEY
      wal:
        compression: gzip