apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp
  labels:
    app: chat
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chatapp
          image: kyczak/chatapp:latest
          ports: 
          - containerPort: 8000
            name: gunicorn
          resources:
            requests: 
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "150Mi"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100          # highest priority to worker nodes
            preference:
              matchExpressions:
              - key: workload
                operator: In
                values: [hlw]
          - weight: 10           # lower priority fallback
            preference:
              matchExpressions:
              - key: workload
                operator: In
                values: [llw]
      # volumes:
      #   - name: chatapp-cache
      #     persistentVolumeClaim:
      #       claimName: chatapp-pvc