apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100          # highest priority to worker nodes
            preference:
              matchExpressions:
              - key: workload
                operator: In
                values: [hlw]
          - weight: 10           # lower priority fallback
            preference:
              matchExpressions:
              - key: workload
                operator: In
                values: [llw]